---
title: "R Notebook"
output:
  html_document:
    df_print: paged
  word_document: default
  html_notebook: default
  pdf_document: default
---

```{r include=FALSE}
# https://community.rstudio.com/t/annotate-ggplot2-with-regression-equation-and-r-squared/6112/7
# https://stackoverflow.com/questions/45185481/how-to-draw-a-function-on-a-scatter-plot-in-ggplot

library(ggplot2)
library(tibble)
library(dplyr)

Data <- tibble(read.csv("~/github/Physics-Graphs/Data.csv"))

Data <- Data %>% 
  mutate(logx = log(x,10)) %>% 
  mutate(logy = log(y,10)) %>% 
  mutate(xre = 1/x) %>%
  mutate(yre = 1/y)

Data2 = head(Data,11) 
Data2 = tail(Data2,10) 


```

```{r}
plot <- ggplot(Data, aes(x=x, y= y)) + geom_point()

plot + xlab("Light Intesity (lx)") + ylab("Potential Difference (V)")

```

```{r}
plot2 <- ggplot(head(Data,11), aes(x=logx, y= y)) + 
  geom_point()+
  xlab("log(Light Intesity (lx))") + 
  ylab("Potential Difference (V)")

plot2

```

```{r}
plot3 <- ggplot(head(Data,11), aes(x=xre, y= y)) + 
  geom_point() + 
  geom_smooth(method = "lm", formula=y~x, se = TRUE) +
  xlab("1/(Light Intesity (lx))") + 
  ylab("Potential Difference (V)")

plot3

ggplotRegression <- function(dat, xvar, yvar){
  
  fml <- paste(yvar, "~", xvar)

  fit <- lm(fml, dat)
  
  ggplot(fit$model, aes_string(x = names(fit$model)[2], y = names(fit$model)[1])) + 
    geom_point() +
    stat_smooth(method = "lm" ,col = "red") +
    labs(title = paste("Adj R2 = ",signif(summary(fit)$adj.r.squared, 5),
                       "Intercept =",signif(fit$coef[[1]],5 ),
                       " Slope =",signif(fit$coef[[2]], 5),
                       " P =",signif(summary(fit)$coef[2,4], 5)))
}
ggplotRegression(head(Data,11), "xre", "y")

```
```{r}
plot3 = ggplot(data.frame(x = c(0, 4)), aes(x = x))  +
  stat_function(fun = function(x) 7.1724*(x^-1), color = "blue", size = 2)+
  geom_point(data = Data2, aes(x, y))

plot3

```



